# Independent settings for the local costmap
local_costmap:

  update_frequency : 2.5
  publish_frequency: 2.5
  max_obstacle_height: 2

  static_map    : false
  rolling_window: true
  width         : 4.0
  height        : 4.0
  resolution    : 0.05

  plugins:
    - name: rgbd_obstacle_layer
      type: 'spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer'
    - name: obstacle_layer
      type: 'costmap_2d::CurrentObstacleLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'

  rgbd_obstacle_layer:
    enabled:               true
    voxel_decay:           0.5     #seconds if linear, e^n if exponential
    decay_model:           0      #0=linear, 1=exponential, -1=persistent
    voxel_size:            0.05   #meters
    track_unknown_space:   true   #default space is unknown
    observation_persistence: 1.0  #seconds
    max_obstacle_height:   2.0    #meters
    unknown_threshold:     15     #voxel height
    mark_threshold:        0      #voxel height
    update_footprint_enabled: true
    combination_method:    1      #1=max, 0=override
    obstacle_range:        3.0    #meters
    origin_z:              0.0    #meters
    publish_voxel_map:     true   # default off
    transform_tolerance:   0.2    # seconds
    mapping_mode:          false  # default off, saves map not for navigation
    map_save_duration:     60     #default 60s, how often to autosave
    observation_sources:   rgbd1_clear rgbd1_mark
    rgbd1_mark:
      data_type: PointCloud2
      topic: /xtion/filtered/points
      marking: true
      clearing: false
      min_obstacle_height: 0.1     #default 0, meters
      max_obstacle_height: 2.0     #defaule 3, meters
      expected_update_rate: 0.0    #default 0, if not updating at this rate at least, remove from buffer
      observation_persistence: 0.0 #default 0, use all measurements taken during now-value, 0=latest 
      inf_is_valid: false          #default false, for laser scans
      clear_after_reading: true    #default false, clear the buffer after the layer gets readings from it
      voxel_filter: true           #default off, apply voxel filter to sensor, recommend on 
    rgbd1_clear:
      data_type: PointCloud2
      topic: /xtion/filtered/points
      marking: false
      clearing: true
      min_z: 0.1                   #default 0, meters
      max_z: 7.0                   #default 10, meters
      vertical_fov_angle: 1.2      #default 0.7, radians
      horizontal_fov_angle: 1.2   #default 1.04, radians
      decay_acceleration: 16       #default 0, 1/s^2. If laser scanner MUST be 0
      model_type: 0                #default 0 (depth camera). Use 1 for 3D Lidar

  obstacle_layer:
    enabled: true
    observation_sources: sensor_scan_clf #point_cloud_sensor1 point_cloud_sensor0
    track_unknown_space: true
    #combination_method: 0 # can erase static layer
    #point_cloud_sensor0: {sensor_frame: xtion_link, data_type: PointCloud2, topic: /xtion/filtered/points, marking: true, clearing: false, min_obstacle_height: 0.05}
    #point_cloud_sensor1: {sensor_frame: xtion_link, data_type: PointCloud2, topic: /xtion/filtered/points, marking: false, clearing: true, min_obstacle_height: -1.0}

    sensor_scan_clf:
      sensor_frame: base_laser_link
      data_type: LaserScan
      topic: /scan_clf
      expected_update_rate: 5.0
      observation_persistence: 1.0
      inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 4.0
      obstacle_range: 3.0

  obstacle_sonar_layer:
    enabled: true
    observation_sources: sonar_max_range_cloud sonar_cloud
    #combination_method: 1

    sonar_cloud:
      sensor_frame: base_link
      data_type: PointCloud2
      topic: sonar_cloud
      expected_update_rate: 1.0
      observation_persistence: 0.0
      marking: true
      clearing: true
      raytrace_range: 3
      obstacle_range: 2
      min_obstacle_height: -0.1
      max_obstacle_height: 1.8

    sonar_max_range_cloud:
      sensor_frame: base_link
      data_type: PointCloud2
      topic: sonar_max_range_cloud
      expected_update_rate: 1.0
      observation_persistence: 0.0
      marking: false
      clearing: true
      raytrace_range: 4
      obstacle_range: 0
      min_obstacle_height: -0.1
      max_obstacle_height: 1.8

  footprint_layer:
    enabled: true

  inflation_layer:
    enabled            : true
    inflation_radius   : 0.3
    cost_scaling_factor: 6

### Biron

#local_costmap:
  #global_frame: /map
 # robot_base_frame: /base_link
 # observation_sources: laser_scan_sensor point_cloud_sensor0 point_cloud_sensor1
#  static_map: false
#  rolling_window: true
#  width: 3.0
#  height: 3.0
#  resolution: 0.05
#  map_type: costmap
#  transform_tolerance: 0.2
