#local planner
base_local_planner: base_local_planner/TrajectoryPlannerROS

### Biron
TrajectoryPlannerROS:

# Set the acc.eleration limits of the robot - "most important thing"
  acc_lim_x: 0.6                    
  acc_lim_theta: !degrees 70.0      

# Set the velocity limits of the robot
  max_vel_x: 0.55                   
  min_vel_x: 0.0                  
  max_vel_theta: !degrees 80.0      
  min_vel_theta: !degrees -80.0               
  min_in_place_vel_theta: !degrees 45.0 

# Notice that this velocity is set to be negative. A bit confusing admittedly.
  escape_vel: 0.0                 # -0.1

# p2os is no holonomic robot.
  holonomic_robot: false            # true

# ---- Goal tolerance parameters
  yaw_goal_tolerance: 0.2           # 0.25 rad = ~15 degree 
  xy_goal_tolerance: 0.1           # 0.2
  latch_xy_goal_tolerance: false     # false  -- If goal tolerance is latched, if the robot ever reaches the goal xy location it will simply rotate in place, even if it ends up outside the goal tolerance while it is doing so.
  
# ---- Foward simulation parameters
# We'll configure how long and with what granularity we'll forward simulate trajectories  
  sim_time: 1.6                     # 1.6 -- setting it higher can result in slightly smoother trajectories
  sim_granularity: 0.025            # 0.025
  angular_sim_granularity: 0.05    # 0.025
  vx_samples: 10                    # 3
  vtheta_samples: 20                # 20


# ---- Parameters for scoring trajectories
  meter_scoring: true              # false -- distance in meter or cells
  pdist_scale: 1.2                 # 
  gdist_scale: 0.85                  # 
  occdist_scale: 0.02               # 0.01 -- weighting how much controller should avoid obstacles
  heading_lookahead: 0.325          # 0.325
  heading_scoring: true            # false
  heading_scoring_timestep: 0.8     # 0.8 -- only with heading_scoring true
  dwa: false                         # true -- false if robot has low acceleration limits
  publish_cost_grid_pc: true        # false
  global_frame_id: odom             # odom

# --- Oscillation prevention parameters
  oscillation_reset_dist: 0.1      # 0.05
  prune_plan: true # Eat up the plan as the robot moves along it

